### ISSUE TITLE
Feature Requests

### ISSUE THREAD

**Issue by chriscantu** [poiati/gmongo#2]
Hello Paulo,

I have been looking at your documentation on Github and on your site.  I can't seem to find three features, pagination, sorting and find by id.  

I have been able to get pagination to work by following the Java Driver syntax.  However, I have not been able to get find by id to work.  I tried db.collection.findOne(_id: id) but this does not return any thing.  In addition, I tried to use the Java syntax db.collection.findOne( "_id", new ObjectId(id)) but that didn't work either. 

Would it be possible to inject "findById" to the collection object?

Also, would it be possible to have a simpler api for paginating and sorting?  I don't mind trying to hack something out and submit a patch.  I was thinking of something like this db.collection.find([skip:0, limit:10, sort: "asc", orderBy: "lastName"]).  

Thoughts?

**Comment by jondejong** [comment]
I'm a little late to the party here, but in case anyone else finds this searching for how to do this, here's some help:

In the example @svaret provided, _id is being queried against a string, but it is an ObjectId (org.bson.types.ObjectId). The example will work with this change:

db.song.update([_id: new ObjectId("511048380364c13f5505c036")], [$set:[title: "GGGGGG"]])

ObjectId has a constructor that takes the string representation and turns converts it back into an ObjectId
