### ISSUE TITLE
Any chance of a mongo driver upgrade

### ISSUE THREAD

**Issue by davydotcom** [poiati/gmongo#28]
The java mongo driver has some features we need in 2.13 any chance this plugin could be modded to support?

**Comment by poiati** [comment]
Yes, I will work on that in this weekend. What feature exactly are you talking about?

**Comment by davydotcom** [comment]
supporting mongo 3.0 series with wiretiger engine so really need it to be on 2.13.0 minimum
--
David Estes

On February 26, 2015 at 2:26:32 PM, Paulo Gabriel Poiati (notifications@github.com) wrote:

Yes, I will work on that in this weekend. What feature exactly are you talking about?

**Comment by poiati** [comment]
davydotcom,  plz try version 1.4, it's already in the maven repo.
